services:
  api:
    image: "ghcr.io/nikiforidi/picovpn-api:release"
    container_name: "api"
    hostname: "api"
    command: /code/api
    ports:
      - 8080:8080
    volumes:
      - /Users/anatolio/picovpn/picovpn/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem:ro
      - /Users/anatolio/picovpn/picovpn/privkey.pem:/etc/letsencrypt/live/picovpn.ru/privkey.pem:ro

  app:
    image: ghcr.io/nikiforidi/picovpn-app:release
    container_name: "app"
    hostname: "app"
    volumes:
      - /Users/anatolio/picovpn/picovpn/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem:ro
      - /Users/anatolio/picovpn/picovpn/privkey.pem:/etc/letsencrypt/live/picovpn.ru/privkey.pem:ro
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off;'
    depends_on:
      - api
  