services:
  db:
    image: "postgres:alpine"
    container_name: "db"
    hostname: "db"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=njVys55V4r2U
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  api:
    image: "ghcr.io/nikiforidi/picovpn-api:release"
    container_name: "api"
    hostname: "api"
    command: /code/api
    expose:
      - 8080
    volumes:
      - /etc/letsencrypt/live/picovpn.ru/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem:ro
      - /etc/letsencrypt/live/picovpn.ru/privkey.pem:/etc/letsencrypt/live/picovpn.ru/privkey.pem:ro
      - ./entrypoint.sh:/code/entrypoint.sh:ro
    entrypoint: /code/entrypoint.sh
    depends_on:
      - db
    environment:
      - TG_BOT_TOKEN=7602027535:AAGrPptEC__CbwGqT-6vFpc-SdnEBAAtiSY
      - POSTGRES_PASSWORD=njVys55V4r2U
  app:
    image: ghcr.io/nikiforidi/picovpn-app:release
    container_name: "app"
    hostname: "app"
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off;'
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt/live/picovpn.ru/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem:ro
      - /etc/letsencrypt/live/picovpn.ru/privkey.pem:/etc/letsencrypt/live/picovpn.ru/privkey.pem:ro
